name: Build latex
description: Run latex builds twice to ensure proper chapters

runs:
  using: 'composite'
  steps:
    - name: Compile documentation LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: documentation
        root_file: main.tex
    - name: Compile documentation LaTeX twice
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: documentation
        root_file: main.tex

    - name: Compile presentation LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: presentation
        root_file: main.tex
    - name: Compile presentation LaTeX twice
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: presentation
        root_file: main.tex