name: Build rust
description: Build rust with release flag

runs:
  using: 'composite'
  steps:
    - name: Build Rust Project
      shell: bash
      run: |
        cd rust
        cargo build --all --release
