name: Build and Package

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile documentation LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: documentation
          root_file: main.tex
      - name: Compile documentation LaTeX twice
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: documentation
          root_file: main.tex

      - name: Compile presentation LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: presentation
          root_file: main.tex
      - name: Compile presentation LaTeX twice
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: presentation
          root_file: main.tex

      - name: Move documents
        run: |
          mv documentation/main.pdf main_document.pdf
          mv presentation/main.pdf presentation_document.pdf

      - name: Build Rust Project
        run: |
          cd rust
          cargo build --release

      - name: Zip Artifacts
        run: |
          git archive -o artifacts.zip HEAD --add-file=main_document.pdf --add-file=presentation_document.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts1
          path: artifacts.zip
