name: Master Branch workflow
# Checkout repo, run latex bilds, rust build and package archive

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build latex
        uses: ./.github/actions/build-latex

      - name: Move documents
        run: |
          mv documentation/main.pdf Rust-Preuss-Schilter-Documentation.pdf
          mv presentation/main.pdf Rust-Preuss-Schilter-Presentation.pdf

      - name: Build rust
        uses: ./.github/actions/build-rust

      - name: Prepare release Artifacts
        run: |
          git archive -o artifacts.zip HEAD --add-file=Rust-Preuss-Schilter-Documentation.pdf --add-file=Rust-Preuss-Schilter-Presentation.pdf

      - name: Unzip into release folder thanks to https://github.com/actions/upload-artifact/issues/39
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq artifacts.zip -d release-artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rust-Preuss-Schilter
          path: release-artifacts/
